[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
rootDirectory = "backend"
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300

[[services.envs]]
DATABASE_URL = "${{PostgreSQL.DATABASE_URL}}"
JWT_SECRET = "your-super-secret-jwt-key-min-32-chars"
NODE_ENV = "production"

[[services]]
name = "frontend"  
rootDirectory = "frontend"
buildCommand = "npm install && npm run build"
startCommand = "npm run start"

[[services.envs]]
VITE_API_URL = "${{backend.RAILWAY_PUBLIC_DOMAIN}}"

[[databases]]
name = "PostgreSQL"
plugin = "postgresql"